In [1]:
import numpy as np

In [55]:
#basics

a = np.array([1,2,3], dtype='int8')
a

array([1, 2, 3], dtype=int8)

In [45]:
b = np.array([[1.2,3.4,81],[4.2,6.4,1.0000001]], dtype='float32')
b

array([[ 1.2      ,  3.4      , 81.       ],
       [ 4.2      ,  6.4      ,  1.0000001]], dtype=float32)

In [25]:
# Dimensions

b.ndim

2

In [27]:
# Shape
print(b.shape)
print(b.shape[0])

(2, 3)
2


In [34]:
# Get type

print(a.dtype)
print(b.dtype)

int32
float16


In [ ]:
# get size
a.itemsize 

# total size
a.itemsize * a.size
a.nbytes

3

In [ ]:
a = np.array([1, 2, 3], dtype="int32")
print(a.itemsize)
print(a.nbytes)

4
12


In [67]:
# Default dtypes
a = a = np.array([1, 2, 3])
print(a.dtype)

a = a = np.array([1.0, 2, 3])
print(a.dtype)

int32
float64


Accessing Elements

In [70]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a.shape)
print(a)

(2, 7)
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [87]:
# Access specific element

a[1,4]  #12
a[0,2:6]  #3-6
a[0,-1] #7

a[0] #first row
a[0,:]

# get a column
a[:,0]

a[0,1::2]
a[0, -3:-1]

array([5, 6])

In [95]:
#Change values

a[0][0] = 11
a

a[0,0:3] = [11,22,33]
a

a[1,] = 5
a

array([[11, 22, 33,  4,  5,  6,  7],
       [ 5,  5,  5,  5,  5,  5,  5]])

In [100]:
c = np.array([[[1, 2,3], [3, 4,3]], [[1, 2,3], [3, 4,4]]])
print(c)
c.shape

[[[1 2 3]
  [3 4 3]]

 [[1 2 3]
  [3 4 4]]]


(2, 2, 3)

In [ ]:
c.ndim

3

In [114]:
# 0s matrix

np.zeros((2,3))

# 1s
np.ones((2, 3),dtype='int16')

#any number

np.full((3,2),3)


array([[3, 3],
       [3, 3],
       [3, 3]])

In [117]:
#fulllike

np.full_like(a, 2)

np.full(a.shape, 2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [146]:
#Random decimal numbers
np.random.randint(0,10,(2,3))

array([[1, 3, 1],
       [7, 3, 5]])

In [147]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [170]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [182]:
a = np.array([[1,2],[3,"4.5"]],dtype=np.float64)
print(a)
print(a.dtype)
print(a[0][0], type(a[0][0]))

[[1.  2. ]
 [3.  4.5]]
float64
1.0 <class 'numpy.float64'>


In [183]:
a = np.array([[1, 2], [3, "4"]])
print(a)
print(a.dtype)
print(a[0][0], type(a[0][0]))

[['1' '2']
 ['3' '4']]
<U11
1 <class 'numpy.str_'>


In [ ]:
a =np.array([[1,2],[3,4]])
print(a)


[[1 2]
 [3 4]]
False


In [190]:
pl = [1,2,3,4,5]
nl = np.array([1,2,3,4,5])

print(pl * 2)
print(nl * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [191]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6,7,8,9,10])
print(a+b)

[ 7  9 11 13 15]


Array Methods

In [213]:
a = np.array([1,2,3])
print(np.append(a, 2))
print(np.append(a, [4,5]))
print(np.append(a, [[4,5],[6,7]]))

a = np.array([[1, 2, 3], [1, 2, 3]])
print(np.append(a, [[4, 5], [6, 7]]))

print(np.insert(a,[0,1],0))
print(np.insert(a, 0, [-2,-1,0]))

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(np.delete(a, 0, 0))
print(np.delete(a, 0, 1))

[1 2 3 2]
[1 2 3 4 5]
[1 2 3 4 5 6 7]
[1 2 3 1 2 3 4 5 6 7]
[0 1 0 2 3 1 2 3]
[-2 -1  0  1  2  3  1  2  3]
[[1 2 3]
 [4 5 6]]
[[4 5 6]]
[[2 3]
 [5 6]]


## Structuring Methods

In [214]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [249]:
print(a.reshape((2,3,2)))
print(a.reshape((1, 6, 2)))

print(a.reshape(12))
print(a.reshape((1,-1)))
print(a.reshape(-1))

print(a.flatten())

print(a.ravel())

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Rvavel vs Flatten

a = np.array([[1,2,3],[4,5,6]])

var = a.flatten()
var[4] = 404
print(var)
print(a) 

var = a.ravel()
var[4] = 404
print(var)
print(a)

[  1   2   3   4 404   6]
[[1 2 3]
 [4 5 6]]
[  1   2   3   4 404   6]
[[  1   2   3]
 [  4 404   6]]


In [255]:
print(a)
for num in a:
    print(num + 1)

for num in a.flat:
    print(num + 1)

[[  1   2   3]
 [  4 404   6]]
[2 3 4]
[  5 405   7]
2
3
4
5
405
7


In [262]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9], [10, 11, 12]])

print(np.concatenate((a1, a2), axis=0))
print(np.concatenate((a1, a2), axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [265]:
print(np.stack((a1,a2)))

print(np.vstack((a1, a2)))
print(np.hstack((a1, a2)))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [267]:
a = np.vstack((a1, a2))
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [270]:
print(np.split(a, 2, axis=0))
print(np.split(a, 3, axis=1))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


Exporting /Importing arrays

In [271]:
np.save("aarray.npy",a)

In [272]:
na = np.load("aarray.npy")
print(na)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
