In [1]:
import numpy as np

In [ ]:
a = np.array([2,5])

distance = np.linalg.norm(a)
#Distance from origin
distance

5.385164807134504

In [ ]:
a = np.array([2,2])
b = np.array([6,2])

difference = a-b
print(difference)
#Euclidean Distance b/w Two points
print(np.linalg.norm(difference))

[-4  0]
4.0


In [ ]:
a = np.array([1,2,3])
a+1

a = np.array([1, 2, 3])
a - 1

a = np.array([1, 2, 3])
a * 2

a = np.array([2, 6, 10])
a / 2

In [26]:
a = np.array([2, 6, 10])
b = np.array([1, 2, 3])

print(a+b)
print(a - b)

[ 3  8 13]
[1 4 7]


In [ ]:
data = np.array([[1,2],[4,5],[6,7]])
data + np.array([1, 2])

array([[2, 4],
       [5, 7],
       [7, 9]])

In [41]:
a = np.array([2, 6, 10])
b = np.array([1, 2, 3])

np.dot(a.T, b)

44

In [47]:
sum(a.T * b)

44