In [1]:
import numpy as np

In [7]:
arr = np.array([1,2,3])



In [9]:
arr

array([1, 2, 3])

In [10]:
type(arr)

numpy.ndarray

In [12]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr1.shape

(2, 3)

In [30]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.ones(shape=(3,2))

(3, 2)

In [34]:
np.ones.__code__

<code object ones at 0x000001F3765FDBB0, file "c:\Users\nithi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\numeric.py", line 136>

In [36]:
import numpy.core.multiarray as multiarray

In [ ]:
a = multiarray.empty((3,2))


In [38]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
multiarray.copyto(a, 2)

In [41]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.arange(5,13,0.1)

array([ 5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,
        6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,
        7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,
        8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,
        9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4,
       10.5, 10.6, 10.7, 10.8, 10.9, 11. , 11.1, 11.2, 11.3, 11.4, 11.5,
       11.6, 11.7, 11.8, 11.9, 12. , 12.1, 12.2, 12.3, 12.4, 12.5, 12.6,
       12.7, 12.8, 12.9])

In [50]:
np.linspace(10,12,100)

array([10.        , 10.02020202, 10.04040404, 10.06060606, 10.08080808,
       10.1010101 , 10.12121212, 10.14141414, 10.16161616, 10.18181818,
       10.2020202 , 10.22222222, 10.24242424, 10.26262626, 10.28282828,
       10.3030303 , 10.32323232, 10.34343434, 10.36363636, 10.38383838,
       10.4040404 , 10.42424242, 10.44444444, 10.46464646, 10.48484848,
       10.50505051, 10.52525253, 10.54545455, 10.56565657, 10.58585859,
       10.60606061, 10.62626263, 10.64646465, 10.66666667, 10.68686869,
       10.70707071, 10.72727273, 10.74747475, 10.76767677, 10.78787879,
       10.80808081, 10.82828283, 10.84848485, 10.86868687, 10.88888889,
       10.90909091, 10.92929293, 10.94949495, 10.96969697, 10.98989899,
       11.01010101, 11.03030303, 11.05050505, 11.07070707, 11.09090909,
       11.11111111, 11.13131313, 11.15151515, 11.17171717, 11.19191919,
       11.21212121, 11.23232323, 11.25252525, 11.27272727, 11.29292929,
       11.31313131, 11.33333333, 11.35353535, 11.37373737, 11.39

In [51]:
arr1 = np.array([1,2,3])
arr2 = np.array([3, 4, 5])

arr1, arr2

(array([1, 2, 3]), array([3, 4, 5]))

In [52]:
arr3 = arr1
arr4 = arr1.copy()

In [54]:
arr1 = np.array([1, 5, 3])

In [56]:
arr3, arr4

(array([1, 2, 3]), array([1, 2, 3]))

In [60]:
arr1

array([1, 5, 3])

In [59]:
arr3 = np.array([7, 2, 3])

In [63]:
arr3[0] = 55

In [65]:
a = np.array([1, 2, 3])
b=a

In [66]:
a,b

(array([1, 2, 3]), array([1, 2, 3]))

In [67]:
a[0] = 74

In [72]:
a,b

(array([55,  4,  3]), array([74,  2,  3]))

In [69]:
a = np.array([5,4,3])

In [71]:
a[0]=55

In [76]:
import time
time.time()

1756016928.0441916